services:
  marketmafioso:
    image: ghcr.io/franfkntastic/marketmafioso-server:latest
    restart: unless-stopped
    ports:
      - "5088:8080"
    env_file:
      - ./marketmafioso.env
    volumes:
      - ./data/marketmafioso:/data
